resources:
  - url: http://127.0.0.1:5000/device-health-card.js
    type: module
views:
  - cards:
      - type: custom:device-health-card
        name: DeviceHealth Card Development
        entity: sun.sun
        test_gui: true
